pragma solidity 0.4.24;

import "../zeppelin/ownership/Ownable.sol";
import "./VreoToken.sol";


/// @title VreoTokenBounty
/// @author Autogenerated from a Dia UML diagram
contract VreoTokenBounty is Ownable {

    VreoToken public token;

    /// @dev Log entry on token distributed
    /// @param recipient An Ethereum address
    /// @param amount A positive number
    event TokenDistributed(address recipient, uint amount);

    /// @dev Constructor
    /// @param _token A VreoToken
    constructor(VreoToken _token) public {
        require(address(_token) != address(0));

        token = _token;
    }

    /// @dev Distribute tokens
    /// @param _recipients A list where each entry is an Ethereum address
    /// @param _amounts A list where each entry is a positive number
    function distributeTokens(address[] _recipients, uint[] _amounts) public onlyOwner {
        require(_recipients.length == _amounts.length);

        for (uint i = 0; i < _recipients.length; ++i) {
            require(_amounts[i] <= token.balanceOf(this));  // TODO: superfluous

            token.transfer(_recipients[i], _amounts[i]);

            emit TokenDistributed(_recipients[i], _amounts[i]);
        }
    }

}

