pragma solidity 0.4.24;

import "../zeppelin/token/ERC20/CappedToken.sol";
import "../zeppelin/token/ERC20/PausableToken.sol";
import "../zeppelin/token/ERC20/BurnableToken.sol";


/// @title VreoToken
/// @author Autogenerated from a Dia UML diagram
contract VreoToken is CappedToken, PausableToken, BurnableToken {

    uint public constant TOTAL_TOKEN_CAP = 700000000e18;  // = 700.000.000 e18

    string public name = "Vreo MTC";
    string public symbol = "MTC";
    uint8 public decimals = 18;

    /// @dev Constructor
    constructor() public CappedToken(TOTAL_TOKEN_CAP) {
    }

    /// @dev Burn
    /// @param _value A positive number
    function burn(uint _value) public whenNotPaused {
        super.burn(_value);
    }

}

