pragma solidity 0.4.24;

import "Crowdsale.sol";


/// @title BaseCrowdsale
/// @author Autogenerated from a Dia UML diagram
contract BaseCrowdsale is Crowdsale {

    /// @dev Tokens available
    /// @param _amount A positive number
    /// @return True or false
    function tokensAvailable(uint _amount) public returns (bool) {
        require(IMPLEMENTATION);
    }

}

