pragma solidity 0.4.24;

import "Crowdsale.sol";


/// @title TokenCappedCrowdsale
/// @author Autogenerated from a Dia UML diagram
contract TokenCappedCrowdsale is Crowdsale {

    uint public remainingTokens;

    /// @dev Constructor
    /// @param _cap A positive number
    constructor(uint _cap) public {
        require(IMPLEMENTATION);
    }

    /// @dev Deliver tokens
    /// @param _beneficiary An Ethereum address
    /// @param _tokenAmount A positive number
    function _deliverTokens(address _beneficiary, uint _tokenAmount) internal {
        require(IMPLEMENTATION);
    }

}

