pragma solidity 0.4.23;

import "Ownable.sol";
import "MintedCrowdsale.sol";
import "TimedCrowdsale.sol";
import "./WhitelistInterface.sol";


/// @title VreoTokenPresale
/// @author Autogenerated from a Dia UML diagram
contract VreoTokenPresale is Ownable, MintedCrowdsale, TimedCrowdsale {

    uint public TOKEN_CAP = 450000000e18; // = 450.000.000 e18
    WhitelistInterface public whitelist;

    /// @dev Log entry on rate changed
    /// @param newRate A positive number
    event RateChanged(uint newRate);

    /// @dev Constructor
    /// @param _token A VreoToken
    /// @param _openingTime A positive number
    /// @param _closingTime A positive number
    /// @param _rate A positive number
    /// @param _wallet An Ethereum address
    constructor(VreoToken _token, uint _openingTime, uint _closingTime, uint _rate, address _wallet) public Crowdsale(_rate, _wallet, _token) TimedCrowdsale(_openingTime, _closingTime) {
        require(IMPLEMENTATION);
    }

    /// @dev Set rate
    /// @param _newRate A positive number
    function setRate(uint _newRate) public onlyOwner {
        require(IMPLEMENTATION);
    }

    /// @dev Buy tokens
    /// @param _beneficiary An Ethereum address
    function buyTokens(address _beneficiary) public payable {
        require(IMPLEMENTATION);
    }

    /// @dev Pre validate purchase
    /// @param _beneficiary An Ethereum address
    /// @param _weiAmount A positive number
    function _preValidatePurchase(address _beneficiary, uint _weiAmount) internal {
        require(IMPLEMENTATION);
    }

    /// @dev Post validate purchase
    /// @param _beneficiary An Ethereum address
    /// @param _weiAmount A positive number
    function _postValidatePurchase(address _beneficiary, uint _weiAmount) internal {
        require(IMPLEMENTATION);
    }

    /// @dev Deliver tokens
    /// @param _beneficiary An Ethereum address
    /// @param _tokenAmount A positive number
    function _deliverTokens(address _beneficiary, uint _tokenAmount) internal {
        require(IMPLEMENTATION);
    }

    /// @dev Process purchase
    /// @param _beneficiary An Ethereum address
    /// @param _tokenAmount A positive number
    function _processPurchase(address _beneficiary, uint _tokenAmount) internal {
        require(IMPLEMENTATION);
    }

    /// @dev Update purchasing state
    /// @param _beneficiary An Ethereum address
    /// @param _weiAmount A positive number
    function _updatePurchasingState(address _beneficiary, uint _weiAmount) internal {
        require(IMPLEMENTATION);
    }

    /// @dev Get token amount
    /// @param _weiAmount A positive number
    /// @return A positive number
    function _getTokenAmount(uint _weiAmount) internal view returns (uint) {
        require(IMPLEMENTATION);
    }

    /// @dev Forward funds
    function _forwardFunds() internal {
        require(IMPLEMENTATION);
    }

    /// @dev Finalization
    function finalization() internal {
        require(IMPLEMENTATION);
    }

}

