pragma solidity 0.4.24;

import "CappedToken.sol";
import "PausableToken.sol";
import "BurnableToken.sol";


/// @title VreoToken
/// @author Autogenerated from a Dia UML diagram
contract VreoToken is CappedToken, PausableToken, BurnableToken {

    string public name = "Vreo MTC";
    string public symbol = "MTC";
    uint8 public decimals = 18;

    /// @dev Constructor
    constructor() public CappedToken(700000000e18) {
        require(IMPLEMENTATION);
    }

    /// @dev Burn
    /// @param _value A positive number
    function burn(uint _value) public whenNotPaused {
        require(IMPLEMENTATION);
    }

}

